### PR TITLE
Fix GitHub Workflows

### PR DESCRIPTION
**Pull request by moogle19**
This switches the old unmaintained `setup-elixir` action to the new one (maintained by Erlef).
Also updated the used Elixir / Erlang version to 2 most recent ones.

### CODE REVIEW

**Comment by josevalim** [comment]
@moogle19 let's remove them (credo, dialyzer) and let's comment out the --check-formatted for now. We can format it and add it back later on so we don't do too many changes at once!

**Comment by moogle19** [comment]
@josevalim I also remove the `excoveralls` deps, because the other ecto project also doesn't use it.

**Comment by josevalim** [comment]
@moogle19 beautiful. So what do you want to do? Do you want to wait for access on tds_encoding or do you want to comment out otp 24 for now?

**Comment by josevalim** [comment]
@moogle19 can it be because of a cache? If you compile the NIF in Erlang/OTP 23, then it will actually work on Erlang/OTP 24 as they have the major version. So if for some reason there is a cached version of it somewhere on CI, it will work. Are you caching? If so, can you make sure the OTP version is part of the cache?

Also, please run `mix deps.unlock --unused` to fix the other CI failure.

**Comment by moogle19** [comment]
@josevalim 
I think it was a cache issue.

I copied the action from `postgrex` which uses [restore-keys](https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows#matching-a-cache-key), which are like a fallback, when the main key doesn't match. I tested it on another branch and now it works like expected.

**Comment by josevalim** [comment]
Beautiful @moogle19! So do you want to comment out 24 for now? Or we wait to merge this?

**Comment by moogle19** [comment]
@josevalim 
Yes, sorry. Because the `ex_doc` version was bumped, the `earmark` dependency is no longer needed (uses `earmark_parser` now).
I just removed it from the `mix.lock` file.

**Comment by moogle19** [comment]
@josevalim 
Thanks!
I will make the `2.2.0` release during the day.

**Pull request merged**
